// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getNextActivitySequence = `-- name: GetNextActivitySequence :one
SELECT COALESCE(MAX(sequence), 0) + 1
FROM workspace_activity_events
WHERE workspace_id = $1
  AND feature_id   = $2
  AND task_id      = $3
`

type GetNextActivitySequenceParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	FeatureID   pgtype.UUID `json:"feature_id"`
	TaskID      pgtype.UUID `json:"task_id"`
}

// Returns the next sequence number for task-scoped activity events.
func (q *Queries) GetNextActivitySequence(ctx context.Context, arg GetNextActivitySequenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, getNextActivitySequence, arg.WorkspaceID, arg.FeatureID, arg.TaskID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertActivityEvent = `-- name: InsertActivityEvent :one
INSERT INTO workspace_activity_events (
    workspace_id,
    scope_type,
    feature_id,
    feature_name,
    task_id,
    task_name,
    action,
    actor,
    occurred_at,
    note,
    sequence,
    raw_event
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id
`

type InsertActivityEventParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	ScopeType   string      `json:"scope_type"`
	FeatureID   pgtype.UUID `json:"feature_id"`
	FeatureName *string     `json:"feature_name"`
	TaskID      pgtype.UUID `json:"task_id"`
	TaskName    *string     `json:"task_name"`
	Action      *string     `json:"action"`
	Actor       *string     `json:"actor"`
	OccurredAt  *string     `json:"occurred_at"`
	Note        *string     `json:"note"`
	Sequence    int32       `json:"sequence"`
	RawEvent    []byte      `json:"raw_event"`
}

func (q *Queries) InsertActivityEvent(ctx context.Context, arg InsertActivityEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertActivityEvent,
		arg.WorkspaceID,
		arg.ScopeType,
		arg.FeatureID,
		arg.FeatureName,
		arg.TaskID,
		arg.TaskName,
		arg.Action,
		arg.Actor,
		arg.OccurredAt,
		arg.Note,
		arg.Sequence,
		arg.RawEvent,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
