// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: features.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getFeatureByName = `-- name: GetFeatureByName :one
SELECT
    id,
    workspace_id,
    feature_id,
    feature_name,
    title,
    feature_status,
    current_stage,
    next_action,
    stages,
    source_path,
    source_hash,
    owner,
    created_at,
    updated_at
FROM workspace_features
WHERE workspace_id = $1
  AND feature_name = $2
LIMIT 1
`

type GetFeatureByNameParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	FeatureName string    `json:"feature_name"`
}

func (q *Queries) GetFeatureByName(ctx context.Context, arg GetFeatureByNameParams) (WorkspaceFeature, error) {
	row := q.db.QueryRow(ctx, getFeatureByName, arg.WorkspaceID, arg.FeatureName)
	var i WorkspaceFeature
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FeatureID,
		&i.FeatureName,
		&i.Title,
		&i.FeatureStatus,
		&i.CurrentStage,
		&i.NextAction,
		&i.Stages,
		&i.SourcePath,
		&i.SourceHash,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFeature = `-- name: InsertFeature :one
INSERT INTO workspace_features (
    workspace_id,
    feature_id,
    feature_name,
    title,
    feature_status,
    current_stage,
    source_path,
    owner
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, feature_id
`

type InsertFeatureParams struct {
	WorkspaceID   uuid.UUID `json:"workspace_id"`
	FeatureID     uuid.UUID `json:"feature_id"`
	FeatureName   string    `json:"feature_name"`
	Title         string    `json:"title"`
	FeatureStatus *string   `json:"feature_status"`
	CurrentStage  *string   `json:"current_stage"`
	SourcePath    *string   `json:"source_path"`
	Owner         *string   `json:"owner"`
}

type InsertFeatureRow struct {
	ID        uuid.UUID `json:"id"`
	FeatureID uuid.UUID `json:"feature_id"`
}

func (q *Queries) InsertFeature(ctx context.Context, arg InsertFeatureParams) (InsertFeatureRow, error) {
	row := q.db.QueryRow(ctx, insertFeature,
		arg.WorkspaceID,
		arg.FeatureID,
		arg.FeatureName,
		arg.Title,
		arg.FeatureStatus,
		arg.CurrentStage,
		arg.SourcePath,
		arg.Owner,
	)
	var i InsertFeatureRow
	err := row.Scan(&i.ID, &i.FeatureID)
	return i, err
}
