// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: handoff_prs.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const insertHandoffPR = `-- name: InsertHandoffPR :one
INSERT INTO handoff_prs (handoff_id, repo, pr_url, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (handoff_id, repo) DO NOTHING
RETURNING id, handoff_id, repo, pr_url, status, conflict_state, rebase_attempts,
          dispatch_handle, dispatch_nonce, dispatched_at, reenqueue_attempts, created_at
`

type InsertHandoffPRParams struct {
	HandoffID uuid.UUID `json:"handoff_id"`
	Repo      string    `json:"repo"`
	PrURL     *string   `json:"pr_url"`
	Status    string    `json:"status"`
}

// InsertHandoffPR creates a new handoff PR row. ON CONFLICT DO NOTHING is
// idempotent per UNIQUE(handoff_id, repo). Returns nil on conflict.
func (q *Queries) InsertHandoffPR(ctx context.Context, arg InsertHandoffPRParams) (*HandoffPr, error) {
	row := q.db.QueryRow(ctx, insertHandoffPR,
		arg.HandoffID,
		arg.Repo,
		arg.PrURL,
		arg.Status,
	)
	var i HandoffPr
	err := row.Scan(
		&i.ID,
		&i.HandoffID,
		&i.Repo,
		&i.PrURL,
		&i.Status,
		&i.ConflictState,
		&i.RebaseAttempts,
		&i.DispatchHandle,
		&i.DispatchNonce,
		&i.DispatchedAt,
		&i.ReenqueueAttempts,
		&i.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &i, nil
}

const listHandoffPRsByHandoff = `-- name: ListHandoffPRsByHandoff :many
SELECT id, handoff_id, repo, pr_url, status, conflict_state, rebase_attempts,
       dispatch_handle, dispatch_nonce, dispatched_at, reenqueue_attempts, created_at
FROM handoff_prs
WHERE handoff_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListHandoffPRsByHandoff(ctx context.Context, handoffID uuid.UUID) ([]HandoffPr, error) {
	rows, err := q.db.Query(ctx, listHandoffPRsByHandoff, handoffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HandoffPr{}
	for rows.Next() {
		var i HandoffPr
		if err := rows.Scan(
			&i.ID,
			&i.HandoffID,
			&i.Repo,
			&i.PrURL,
			&i.Status,
			&i.ConflictState,
			&i.RebaseAttempts,
			&i.DispatchHandle,
			&i.DispatchNonce,
			&i.DispatchedAt,
			&i.ReenqueueAttempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHandoffPRStatus = `-- name: UpdateHandoffPRStatus :exec
UPDATE handoff_prs
SET status = $2
WHERE id = $1
`

type UpdateHandoffPRStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateHandoffPRStatus(ctx context.Context, arg UpdateHandoffPRStatusParams) error {
	_, err := q.db.Exec(ctx, updateHandoffPRStatus, arg.ID, arg.Status)
	return err
}

const updateHandoffPRConflictState = `-- name: UpdateHandoffPRConflictState :exec
UPDATE handoff_prs
SET conflict_state = $2
WHERE id = $1
`

type UpdateHandoffPRConflictStateParams struct {
	ID            uuid.UUID `json:"id"`
	ConflictState string    `json:"conflict_state"`
}

func (q *Queries) UpdateHandoffPRConflictState(ctx context.Context, arg UpdateHandoffPRConflictStateParams) error {
	_, err := q.db.Exec(ctx, updateHandoffPRConflictState, arg.ID, arg.ConflictState)
	return err
}

const listResolvingHandoffPRs = `-- name: ListResolvingHandoffPRs :many
SELECT id, handoff_id, repo, pr_url, status, conflict_state, rebase_attempts,
       dispatch_handle, dispatch_nonce, dispatched_at, reenqueue_attempts, created_at
FROM handoff_prs
WHERE conflict_state = 'resolving'
`

// ListResolvingHandoffPRs returns handoff PRs currently in rebase dispatch.
func (q *Queries) ListResolvingHandoffPRs(ctx context.Context) ([]HandoffPr, error) {
	rows, err := q.db.Query(ctx, listResolvingHandoffPRs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HandoffPr{}
	for rows.Next() {
		var i HandoffPr
		if err := rows.Scan(
			&i.ID,
			&i.HandoffID,
			&i.Repo,
			&i.PrURL,
			&i.Status,
			&i.ConflictState,
			&i.RebaseAttempts,
			&i.DispatchHandle,
			&i.DispatchNonce,
			&i.DispatchedAt,
			&i.ReenqueueAttempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
