// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: handoffs.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const insertHandoff = `-- name: InsertHandoff :one
INSERT INTO handoffs (workspace_id, feature_id, status)
VALUES ($1, $2, 'open')
ON CONFLICT (feature_id) DO NOTHING
RETURNING id, workspace_id, feature_id, mgmt_pr_url, status, created_at, finalized_at
`

type InsertHandoffParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	FeatureID   uuid.UUID `json:"feature_id"`
}

// InsertHandoff creates a new handoff row. ON CONFLICT DO NOTHING makes this
// idempotent — the UNIQUE(feature_id) constraint is the multi-instance trigger guard.
// Returns nil when the handoff already existed (conflict).
func (q *Queries) InsertHandoff(ctx context.Context, arg InsertHandoffParams) (*Handoff, error) {
	row := q.db.QueryRow(ctx, insertHandoff, arg.WorkspaceID, arg.FeatureID)
	var i Handoff
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FeatureID,
		&i.MgmtPrURL,
		&i.Status,
		&i.CreatedAt,
		&i.FinalizedAt,
	)
	if err != nil {
		// pgx returns ErrNoRows when ON CONFLICT DO NOTHING fires.
		return nil, err
	}
	return &i, nil
}

const getHandoffByFeature = `-- name: GetHandoffByFeature :one
SELECT id, workspace_id, feature_id, mgmt_pr_url, status, created_at, finalized_at
FROM handoffs
WHERE feature_id = $1
LIMIT 1
`

func (q *Queries) GetHandoffByFeature(ctx context.Context, featureID uuid.UUID) (Handoff, error) {
	row := q.db.QueryRow(ctx, getHandoffByFeature, featureID)
	var i Handoff
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FeatureID,
		&i.MgmtPrURL,
		&i.Status,
		&i.CreatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const updateHandoffMgmtPRURL = `-- name: UpdateHandoffMgmtPRURL :exec
UPDATE handoffs
SET mgmt_pr_url = $2
WHERE id = $1
`

type UpdateHandoffMgmtPRURLParams struct {
	ID        uuid.UUID `json:"id"`
	MgmtPrURL *string   `json:"mgmt_pr_url"`
}

func (q *Queries) UpdateHandoffMgmtPRURL(ctx context.Context, arg UpdateHandoffMgmtPRURLParams) error {
	_, err := q.db.Exec(ctx, updateHandoffMgmtPRURL, arg.ID, arg.MgmtPrURL)
	return err
}

const finalizeHandoff = `-- name: FinalizeHandoff :exec
UPDATE handoffs
SET status = 'finalized', finalized_at = now()
WHERE id = $1
`

func (q *Queries) FinalizeHandoff(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, finalizeHandoff, id)
	return err
}
