// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tasks.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getTaskByUUID = `-- name: GetTaskByUUID :one
SELECT
    id,
    workspace_id,
    feature_id,
    feature_name,
    task_id,
    task_name,
    title,
    repo,
    status,
    depends_on,
    blocked_reason,
    branch,
    execution,
    pr,
    workspace_pr,
    source_path,
    source_hash,
    owner,
    created_at,
    updated_at
FROM workspace_tasks
WHERE workspace_id = $1
  AND task_id = $2
LIMIT 1
`

type GetTaskByUUIDParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	TaskID      uuid.UUID `json:"task_id"`
}

func (q *Queries) GetTaskByUUID(ctx context.Context, arg GetTaskByUUIDParams) (WorkspaceTask, error) {
	row := q.db.QueryRow(ctx, getTaskByUUID, arg.WorkspaceID, arg.TaskID)
	var i WorkspaceTask
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FeatureID,
		&i.FeatureName,
		&i.TaskID,
		&i.TaskName,
		&i.Title,
		&i.Repo,
		&i.Status,
		&i.DependsOn,
		&i.BlockedReason,
		&i.Branch,
		&i.Execution,
		&i.Pr,
		&i.WorkspacePr,
		&i.SourcePath,
		&i.SourceHash,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const guardedUpdateTaskStatus = `-- name: GuardedUpdateTaskStatus :one
UPDATE workspace_tasks
SET
    status     = $1,
    execution  = COALESCE($2::jsonb, execution),
    updated_at = now()
WHERE workspace_id = $3
  AND task_id      = $4
  AND status       = $5
RETURNING id
`

type GuardedUpdateTaskStatusParams struct {
	NewStatus      *string   `json:"new_status"`
	Execution      []byte    `json:"execution"`
	WorkspaceID    uuid.UUID `json:"workspace_id"`
	TaskID         uuid.UUID `json:"task_id"`
	ExpectedStatus *string   `json:"expected_status"`
}

// Atomic FSM transition: updates status only if the current status matches
// the expected value. Returns the row id if the update succeeded, or no rows
// if another writer won the race (first-push-wins).
func (q *Queries) GuardedUpdateTaskStatus(ctx context.Context, arg GuardedUpdateTaskStatusParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, guardedUpdateTaskStatus,
		arg.NewStatus,
		arg.Execution,
		arg.WorkspaceID,
		arg.TaskID,
		arg.ExpectedStatus,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertTask = `-- name: InsertTask :one
INSERT INTO workspace_tasks (
    workspace_id,
    feature_id,
    feature_name,
    task_id,
    task_name,
    title,
    repo,
    status,
    depends_on,
    branch,
    source_path,
    owner
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, task_id
`

type InsertTaskParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	FeatureID   uuid.UUID `json:"feature_id"`
	FeatureName string    `json:"feature_name"`
	TaskID      uuid.UUID `json:"task_id"`
	TaskName    string    `json:"task_name"`
	Title       string    `json:"title"`
	Repo        *string   `json:"repo"`
	Status      *string   `json:"status"`
	DependsOn   []byte    `json:"depends_on"`
	Branch      *string   `json:"branch"`
	SourcePath  *string   `json:"source_path"`
	Owner       *string   `json:"owner"`
}

type InsertTaskRow struct {
	ID     uuid.UUID `json:"id"`
	TaskID uuid.UUID `json:"task_id"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (InsertTaskRow, error) {
	row := q.db.QueryRow(ctx, insertTask,
		arg.WorkspaceID,
		arg.FeatureID,
		arg.FeatureName,
		arg.TaskID,
		arg.TaskName,
		arg.Title,
		arg.Repo,
		arg.Status,
		arg.DependsOn,
		arg.Branch,
		arg.SourcePath,
		arg.Owner,
	)
	var i InsertTaskRow
	err := row.Scan(&i.ID, &i.TaskID)
	return i, err
}

const listEligibleTasks = `-- name: ListEligibleTasks :many
SELECT t.id, t.workspace_id, t.feature_id, t.feature_name, t.task_id, t.task_name, t.title, t.repo, t.status, t.depends_on, t.blocked_reason, t.branch, t.execution, t.pr, t.workspace_pr, t.source_path, t.source_hash, t.owner, t.created_at, t.updated_at
FROM workspace_tasks t
WHERE t.workspace_id = $1
  AND t.owner = 'go'
  AND t.status = 'ready'
  AND NOT EXISTS (
      SELECT 1
      FROM jsonb_array_elements_text(t.depends_on) AS dep
      WHERE NOT EXISTS (
          SELECT 1
          FROM workspace_tasks dep_task
          WHERE dep_task.workspace_id = t.workspace_id
            AND dep_task.feature_id  = t.feature_id
            AND dep_task.task_name   = dep
            AND dep_task.status      = 'done'
      )
  )
`

// Returns go-owned tasks in 'ready' status whose every dependency task_name
// is already in 'done' status within the same feature.
// Used by T7 (eligibility scan).
func (q *Queries) ListEligibleTasks(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceTask, error) {
	rows, err := q.db.Query(ctx, listEligibleTasks, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceTask{}
	for rows.Next() {
		var i WorkspaceTask
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FeatureID,
			&i.FeatureName,
			&i.TaskID,
			&i.TaskName,
			&i.Title,
			&i.Repo,
			&i.Status,
			&i.DependsOn,
			&i.BlockedReason,
			&i.Branch,
			&i.Execution,
			&i.Pr,
			&i.WorkspacePr,
			&i.SourcePath,
			&i.SourceHash,
			&i.Owner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInReviewTasksForOwner = `-- name: ListInReviewTasksForOwner :many
SELECT
    id,
    workspace_id,
    feature_id,
    feature_name,
    task_id,
    task_name,
    title,
    repo,
    status,
    depends_on,
    blocked_reason,
    branch,
    execution,
    pr,
    workspace_pr,
    source_path,
    source_hash,
    owner,
    created_at,
    updated_at
FROM workspace_tasks
WHERE workspace_id = $1
  AND owner        = $2
  AND status       = 'in_review'
`

type ListInReviewTasksForOwnerParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Owner       *string   `json:"owner"`
}

// Returns tasks in 'in_review' state for a given owner (e.g. 'go').
// Used by the PR-merge poll (T13).
func (q *Queries) ListInReviewTasksForOwner(ctx context.Context, arg ListInReviewTasksForOwnerParams) ([]WorkspaceTask, error) {
	rows, err := q.db.Query(ctx, listInReviewTasksForOwner, arg.WorkspaceID, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceTask{}
	for rows.Next() {
		var i WorkspaceTask
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FeatureID,
			&i.FeatureName,
			&i.TaskID,
			&i.TaskName,
			&i.Title,
			&i.Repo,
			&i.Status,
			&i.DependsOn,
			&i.BlockedReason,
			&i.Branch,
			&i.Execution,
			&i.Pr,
			&i.WorkspacePr,
			&i.SourcePath,
			&i.SourceHash,
			&i.Owner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByFeature = `-- name: ListTasksByFeature :many
SELECT
    id,
    workspace_id,
    feature_id,
    feature_name,
    task_id,
    task_name,
    title,
    repo,
    status,
    depends_on,
    blocked_reason,
    branch,
    execution,
    pr,
    workspace_pr,
    source_path,
    source_hash,
    owner,
    created_at,
    updated_at
FROM workspace_tasks
WHERE workspace_id = $1
  AND feature_id   = $2
ORDER BY task_name
`

type ListTasksByFeatureParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	FeatureID   uuid.UUID `json:"feature_id"`
}

func (q *Queries) ListTasksByFeature(ctx context.Context, arg ListTasksByFeatureParams) ([]WorkspaceTask, error) {
	rows, err := q.db.Query(ctx, listTasksByFeature, arg.WorkspaceID, arg.FeatureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceTask{}
	for rows.Next() {
		var i WorkspaceTask
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FeatureID,
			&i.FeatureName,
			&i.TaskID,
			&i.TaskName,
			&i.Title,
			&i.Repo,
			&i.Status,
			&i.DependsOn,
			&i.BlockedReason,
			&i.Branch,
			&i.Execution,
			&i.Pr,
			&i.WorkspacePr,
			&i.SourcePath,
			&i.SourceHash,
			&i.Owner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
